# Generated by Django 4.1.2 on 2022-10-08 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Name')),
                ('description', models.TextField(max_length=255)),
                ('price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('category', models.TextField(default='', max_length=255)),
                ('hour', models.TimeField(blank=True, null=True)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('image', models.ImageField(default='', upload_to='photos/%y/%m/%d')),
            ],
            options={
                'verbose_name': 'My-Medicine',
                'ordering': ['-price'],
            },
        ),
    ]
